// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: demo/v1/demo.proto

package demov1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "golang-tars/pkg/proto/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Demo 实体
type Demo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Demo ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Demo 名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Demo 描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Demo 状态：1-启用，2-禁用
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 创建时间（Unix 时间戳）
	CreatedAt int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间（Unix 时间戳）
	UpdatedAt     int64 `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demo) Reset() {
	*x = Demo{}
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo) ProtoMessage() {}

func (x *Demo) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo.ProtoReflect.Descriptor instead.
func (*Demo) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{0}
}

func (x *Demo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Demo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Demo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Demo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Demo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Demo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建 Demo 请求
type CreateDemoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Demo 名称（必填，长度 1-100）
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Demo 描述（可选，最大长度 500）
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Demo 状态（必填，只能是 1 或 2）
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemoRequest) Reset() {
	*x = CreateDemoRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemoRequest) ProtoMessage() {}

func (x *CreateDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemoRequest.ProtoReflect.Descriptor instead.
func (*CreateDemoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDemoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDemoRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 创建 Demo 响应
type CreateDemoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 创建的 Demo 对象
	Data          *Demo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemoResponse) Reset() {
	*x = CreateDemoResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemoResponse) ProtoMessage() {}

func (x *CreateDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemoResponse.ProtoReflect.Descriptor instead.
func (*CreateDemoResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDemoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateDemoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateDemoResponse) GetData() *Demo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取 Demo 请求
type GetDemoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Demo ID（必填，大于 0）
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoRequest) Reset() {
	*x = GetDemoRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoRequest) ProtoMessage() {}

func (x *GetDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoRequest.ProtoReflect.Descriptor instead.
func (*GetDemoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{3}
}

func (x *GetDemoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取 Demo 响应
type GetDemoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Demo 对象
	Data          *Demo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoResponse) Reset() {
	*x = GetDemoResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoResponse) ProtoMessage() {}

func (x *GetDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoResponse.ProtoReflect.Descriptor instead.
func (*GetDemoResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{4}
}

func (x *GetDemoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetDemoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetDemoResponse) GetData() *Demo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 更新 Demo 请求
type UpdateDemoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Demo ID（必填，大于 0）
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Demo 名称（可选，如果提供则长度 1-100）
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Demo 描述（可选，最大长度 500）
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Demo 状态（可选，只能是 1 或 2）
	Status        *int32 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDemoRequest) Reset() {
	*x = UpdateDemoRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDemoRequest) ProtoMessage() {}

func (x *UpdateDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDemoRequest.ProtoReflect.Descriptor instead.
func (*UpdateDemoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDemoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDemoRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateDemoRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateDemoRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 更新 Demo 响应
type UpdateDemoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 更新后的 Demo 对象
	Data          *Demo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDemoResponse) Reset() {
	*x = UpdateDemoResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDemoResponse) ProtoMessage() {}

func (x *UpdateDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDemoResponse.ProtoReflect.Descriptor instead.
func (*UpdateDemoResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDemoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateDemoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDemoResponse) GetData() *Demo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除 Demo 请求
type DeleteDemoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Demo ID（必填，大于 0）
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDemoRequest) Reset() {
	*x = DeleteDemoRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDemoRequest) ProtoMessage() {}

func (x *DeleteDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDemoRequest.ProtoReflect.Descriptor instead.
func (*DeleteDemoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDemoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除 Demo 响应
type DeleteDemoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 空数据（可选）
	Data          *v1.Empty `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDemoResponse) Reset() {
	*x = DeleteDemoResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDemoResponse) ProtoMessage() {}

func (x *DeleteDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDemoResponse.ProtoReflect.Descriptor instead.
func (*DeleteDemoResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDemoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteDemoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteDemoResponse) GetData() *v1.Empty {
	if x != nil {
		return x.Data
	}
	return nil
}

// 列表 Demo 请求
type ListDemoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码（可选，默认 1，最小 1）
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量（可选，默认 10，范围 1-100）
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 状态筛选（可选，只能是 1 或 2）
	Status *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// 名称搜索（可选）
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDemoRequest) Reset() {
	*x = ListDemoRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDemoRequest) ProtoMessage() {}

func (x *ListDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDemoRequest.ProtoReflect.Descriptor instead.
func (*ListDemoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{9}
}

func (x *ListDemoRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDemoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDemoRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListDemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 列表数据
type ListDemoData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Demo 列表
	Items []*Demo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 当前页码
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 总记录数
	Total int64 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	// 总页数
	TotalPages    int32 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDemoData) Reset() {
	*x = ListDemoData{}
	mi := &file_demo_v1_demo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDemoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDemoData) ProtoMessage() {}

func (x *ListDemoData) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDemoData.ProtoReflect.Descriptor instead.
func (*ListDemoData) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{10}
}

func (x *ListDemoData) GetItems() []*Demo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListDemoData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDemoData) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDemoData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDemoData) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// 列表 Demo 响应
type ListDemoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 列表数据
	Data          *ListDemoData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDemoResponse) Reset() {
	*x = ListDemoResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDemoResponse) ProtoMessage() {}

func (x *ListDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDemoResponse.ProtoReflect.Descriptor instead.
func (*ListDemoResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{11}
}

func (x *ListDemoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListDemoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDemoResponse) GetData() *ListDemoData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_demo_v1_demo_proto protoreflect.FileDescriptor

const file_demo_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x12demo/v1/demo.proto\x12\ademo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x16common/v1/common.proto\"\xa2\x01\n" +
	"\x04Demo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\x81\x01\n" +
	"\x11CreateDemoRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\vdescription\x12!\n" +
	"\x06status\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x040\x010\x02R\x06status\"e\n" +
	"\x12CreateDemoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.demo.v1.DemoR\x04data\")\n" +
	"\x0eGetDemoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"b\n" +
	"\x0fGetDemoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.demo.v1.DemoR\x04data\"\xd5\x01\n" +
	"\x11UpdateDemoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12%\n" +
	"\x04name\x18\x02 \x01(\tB\f\xfaB\tr\a\x10\x01\x18d\xd0\x01\x01H\x00R\x04name\x88\x01\x01\x122\n" +
	"\vdescription\x18\x03 \x01(\tB\v\xfaB\br\x06\x18\xf4\x03\xd0\x01\x01H\x01R\vdescription\x88\x01\x01\x12(\n" +
	"\x06status\x18\x04 \x01(\x05B\v\xfaB\b\x1a\x060\x010\x02@\x01H\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"e\n" +
	"\x12UpdateDemoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.demo.v1.DemoR\x04data\",\n" +
	"\x11DeleteDemoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"h\n" +
	"\x12DeleteDemoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.common.v1.EmptyR\x04data\"\xa3\x01\n" +
	"\x0fListDemoRequest\x12\x1d\n" +
	"\x04page\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04(\x01@\x01R\x04page\x12(\n" +
	"\tpage_size\x18\x02 \x01(\x05B\v\xfaB\b\x1a\x06\x18d(\x01@\x01R\bpageSize\x12(\n" +
	"\x06status\x18\x03 \x01(\x05B\v\xfaB\b\x1a\x060\x010\x02@\x01H\x00R\x06status\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04nameB\t\n" +
	"\a_status\"\x9b\x01\n" +
	"\fListDemoData\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.demo.v1.DemoR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"k\n" +
	"\x10ListDemoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.demo.v1.ListDemoDataR\x04data2\xe4\x03\n" +
	"\vDemoService\x12^\n" +
	"\n" +
	"CreateDemo\x12\x1a.demo.v1.CreateDemoRequest\x1a\x1b.demo.v1.CreateDemoResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/demo\x12W\n" +
	"\aGetDemo\x12\x17.demo.v1.GetDemoRequest\x1a\x18.demo.v1.GetDemoResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/demo/{id}\x12c\n" +
	"\n" +
	"UpdateDemo\x12\x1a.demo.v1.UpdateDemoRequest\x1a\x1b.demo.v1.UpdateDemoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/demo/{id}\x12`\n" +
	"\n" +
	"DeleteDemo\x12\x1a.demo.v1.DeleteDemoRequest\x1a\x1b.demo.v1.DeleteDemoResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/demo/{id}\x12U\n" +
	"\bListDemo\x12\x18.demo.v1.ListDemoRequest\x1a\x19.demo.v1.ListDemoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/demoB\"Z golang-tars/pkg/proto/demo/v1;demov1b\x06proto3"

var (
	file_demo_v1_demo_proto_rawDescOnce sync.Once
	file_demo_v1_demo_proto_rawDescData []byte
)

func file_demo_v1_demo_proto_rawDescGZIP() []byte {
	file_demo_v1_demo_proto_rawDescOnce.Do(func() {
		file_demo_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)))
	})
	return file_demo_v1_demo_proto_rawDescData
}

var file_demo_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_demo_v1_demo_proto_goTypes = []any{
	(*Demo)(nil),               // 0: demo.v1.Demo
	(*CreateDemoRequest)(nil),  // 1: demo.v1.CreateDemoRequest
	(*CreateDemoResponse)(nil), // 2: demo.v1.CreateDemoResponse
	(*GetDemoRequest)(nil),     // 3: demo.v1.GetDemoRequest
	(*GetDemoResponse)(nil),    // 4: demo.v1.GetDemoResponse
	(*UpdateDemoRequest)(nil),  // 5: demo.v1.UpdateDemoRequest
	(*UpdateDemoResponse)(nil), // 6: demo.v1.UpdateDemoResponse
	(*DeleteDemoRequest)(nil),  // 7: demo.v1.DeleteDemoRequest
	(*DeleteDemoResponse)(nil), // 8: demo.v1.DeleteDemoResponse
	(*ListDemoRequest)(nil),    // 9: demo.v1.ListDemoRequest
	(*ListDemoData)(nil),       // 10: demo.v1.ListDemoData
	(*ListDemoResponse)(nil),   // 11: demo.v1.ListDemoResponse
	(*v1.Empty)(nil),           // 12: common.v1.Empty
}
var file_demo_v1_demo_proto_depIdxs = []int32{
	0,  // 0: demo.v1.CreateDemoResponse.data:type_name -> demo.v1.Demo
	0,  // 1: demo.v1.GetDemoResponse.data:type_name -> demo.v1.Demo
	0,  // 2: demo.v1.UpdateDemoResponse.data:type_name -> demo.v1.Demo
	12, // 3: demo.v1.DeleteDemoResponse.data:type_name -> common.v1.Empty
	0,  // 4: demo.v1.ListDemoData.items:type_name -> demo.v1.Demo
	10, // 5: demo.v1.ListDemoResponse.data:type_name -> demo.v1.ListDemoData
	1,  // 6: demo.v1.DemoService.CreateDemo:input_type -> demo.v1.CreateDemoRequest
	3,  // 7: demo.v1.DemoService.GetDemo:input_type -> demo.v1.GetDemoRequest
	5,  // 8: demo.v1.DemoService.UpdateDemo:input_type -> demo.v1.UpdateDemoRequest
	7,  // 9: demo.v1.DemoService.DeleteDemo:input_type -> demo.v1.DeleteDemoRequest
	9,  // 10: demo.v1.DemoService.ListDemo:input_type -> demo.v1.ListDemoRequest
	2,  // 11: demo.v1.DemoService.CreateDemo:output_type -> demo.v1.CreateDemoResponse
	4,  // 12: demo.v1.DemoService.GetDemo:output_type -> demo.v1.GetDemoResponse
	6,  // 13: demo.v1.DemoService.UpdateDemo:output_type -> demo.v1.UpdateDemoResponse
	8,  // 14: demo.v1.DemoService.DeleteDemo:output_type -> demo.v1.DeleteDemoResponse
	11, // 15: demo.v1.DemoService.ListDemo:output_type -> demo.v1.ListDemoResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_demo_v1_demo_proto_init() }
func file_demo_v1_demo_proto_init() {
	if File_demo_v1_demo_proto != nil {
		return
	}
	file_demo_v1_demo_proto_msgTypes[5].OneofWrappers = []any{}
	file_demo_v1_demo_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_demo_proto_goTypes,
		DependencyIndexes: file_demo_v1_demo_proto_depIdxs,
		MessageInfos:      file_demo_v1_demo_proto_msgTypes,
	}.Build()
	File_demo_v1_demo_proto = out.File
	file_demo_v1_demo_proto_goTypes = nil
	file_demo_v1_demo_proto_depIdxs = nil
}
