// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: demo/v1/demo.proto

package demov1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Demo with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Demo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Demo with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DemoMultiError, or nil if none found.
func (m *Demo) ValidateAll() error {
	return m.validate(true)
}

func (m *Demo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return DemoMultiError(errors)
	}

	return nil
}

// DemoMultiError is an error wrapping multiple validation errors returned by
// Demo.ValidateAll() if the designated constraints aren't met.
type DemoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DemoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DemoMultiError) AllErrors() []error { return m }

// DemoValidationError is the validation error returned by Demo.Validate if the
// designated constraints aren't met.
type DemoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DemoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DemoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DemoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DemoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DemoValidationError) ErrorName() string { return "DemoValidationError" }

// Error satisfies the builtin error interface
func (e DemoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDemo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DemoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DemoValidationError{}

// Validate checks the field values on CreateDemoRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateDemoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDemoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDemoRequestMultiError, or nil if none found.
func (m *CreateDemoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDemoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 100 {
		err := CreateDemoRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) > 500 {
		err := CreateDemoRequestValidationError{
			field:  "Description",
			reason: "value length must be at most 500 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateDemoRequest_Status_InLookup[m.GetStatus()]; !ok {
		err := CreateDemoRequestValidationError{
			field:  "Status",
			reason: "value must be in list [1 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateDemoRequestMultiError(errors)
	}

	return nil
}

// CreateDemoRequestMultiError is an error wrapping multiple validation errors
// returned by CreateDemoRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateDemoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDemoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDemoRequestMultiError) AllErrors() []error { return m }

// CreateDemoRequestValidationError is the validation error returned by
// CreateDemoRequest.Validate if the designated constraints aren't met.
type CreateDemoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDemoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDemoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDemoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDemoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDemoRequestValidationError) ErrorName() string {
	return "CreateDemoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDemoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDemoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDemoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDemoRequestValidationError{}

var _CreateDemoRequest_Status_InLookup = map[int32]struct{}{
	1: {},
	2: {},
}

// Validate checks the field values on CreateDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateDemoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDemoResponseMultiError, or nil if none found.
func (m *CreateDemoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDemoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateDemoResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateDemoResponseMultiError(errors)
	}

	return nil
}

// CreateDemoResponseMultiError is an error wrapping multiple validation errors
// returned by CreateDemoResponse.ValidateAll() if the designated constraints
// aren't met.
type CreateDemoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDemoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDemoResponseMultiError) AllErrors() []error { return m }

// CreateDemoResponseValidationError is the validation error returned by
// CreateDemoResponse.Validate if the designated constraints aren't met.
type CreateDemoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDemoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDemoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDemoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDemoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDemoResponseValidationError) ErrorName() string {
	return "CreateDemoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDemoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDemoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDemoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDemoResponseValidationError{}

// Validate checks the field values on GetDemoRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetDemoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDemoRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetDemoRequestMultiError,
// or nil if none found.
func (m *GetDemoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDemoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetDemoRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetDemoRequestMultiError(errors)
	}

	return nil
}

// GetDemoRequestMultiError is an error wrapping multiple validation errors
// returned by GetDemoRequest.ValidateAll() if the designated constraints
// aren't met.
type GetDemoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDemoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDemoRequestMultiError) AllErrors() []error { return m }

// GetDemoRequestValidationError is the validation error returned by
// GetDemoRequest.Validate if the designated constraints aren't met.
type GetDemoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDemoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDemoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDemoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDemoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDemoRequestValidationError) ErrorName() string { return "GetDemoRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetDemoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDemoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDemoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDemoRequestValidationError{}

// Validate checks the field values on GetDemoResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDemoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDemoResponseMultiError, or nil if none found.
func (m *GetDemoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDemoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDemoResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetDemoResponseMultiError(errors)
	}

	return nil
}

// GetDemoResponseMultiError is an error wrapping multiple validation errors
// returned by GetDemoResponse.ValidateAll() if the designated constraints
// aren't met.
type GetDemoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDemoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDemoResponseMultiError) AllErrors() []error { return m }

// GetDemoResponseValidationError is the validation error returned by
// GetDemoResponse.Validate if the designated constraints aren't met.
type GetDemoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDemoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDemoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDemoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDemoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDemoResponseValidationError) ErrorName() string { return "GetDemoResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetDemoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDemoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDemoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDemoResponseValidationError{}

// Validate checks the field values on UpdateDemoRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateDemoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDemoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDemoRequestMultiError, or nil if none found.
func (m *UpdateDemoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDemoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateDemoRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Name != nil {

		if m.GetName() != "" {

			if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 100 {
				err := UpdateDemoRequestValidationError{
					field:  "Name",
					reason: "value length must be between 1 and 100 runes, inclusive",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Description != nil {

		if m.GetDescription() != "" {

			if utf8.RuneCountInString(m.GetDescription()) > 500 {
				err := UpdateDemoRequestValidationError{
					field:  "Description",
					reason: "value length must be at most 500 runes",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Status != nil {

		if m.GetStatus() != 0 {

			if _, ok := _UpdateDemoRequest_Status_InLookup[m.GetStatus()]; !ok {
				err := UpdateDemoRequestValidationError{
					field:  "Status",
					reason: "value must be in list [1 2]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(errors) > 0 {
		return UpdateDemoRequestMultiError(errors)
	}

	return nil
}

// UpdateDemoRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateDemoRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateDemoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDemoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDemoRequestMultiError) AllErrors() []error { return m }

// UpdateDemoRequestValidationError is the validation error returned by
// UpdateDemoRequest.Validate if the designated constraints aren't met.
type UpdateDemoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDemoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDemoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDemoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDemoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDemoRequestValidationError) ErrorName() string {
	return "UpdateDemoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDemoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDemoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDemoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDemoRequestValidationError{}

var _UpdateDemoRequest_Status_InLookup = map[int32]struct{}{
	1: {},
	2: {},
}

// Validate checks the field values on UpdateDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateDemoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDemoResponseMultiError, or nil if none found.
func (m *UpdateDemoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDemoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateDemoResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateDemoResponseMultiError(errors)
	}

	return nil
}

// UpdateDemoResponseMultiError is an error wrapping multiple validation errors
// returned by UpdateDemoResponse.ValidateAll() if the designated constraints
// aren't met.
type UpdateDemoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDemoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDemoResponseMultiError) AllErrors() []error { return m }

// UpdateDemoResponseValidationError is the validation error returned by
// UpdateDemoResponse.Validate if the designated constraints aren't met.
type UpdateDemoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDemoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDemoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDemoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDemoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDemoResponseValidationError) ErrorName() string {
	return "UpdateDemoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDemoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDemoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDemoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDemoResponseValidationError{}

// Validate checks the field values on DeleteDemoRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteDemoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDemoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDemoRequestMultiError, or nil if none found.
func (m *DeleteDemoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDemoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := DeleteDemoRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteDemoRequestMultiError(errors)
	}

	return nil
}

// DeleteDemoRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteDemoRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteDemoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDemoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDemoRequestMultiError) AllErrors() []error { return m }

// DeleteDemoRequestValidationError is the validation error returned by
// DeleteDemoRequest.Validate if the designated constraints aren't met.
type DeleteDemoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDemoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDemoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDemoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDemoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDemoRequestValidationError) ErrorName() string {
	return "DeleteDemoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDemoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDemoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDemoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDemoRequestValidationError{}

// Validate checks the field values on DeleteDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDemoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDemoResponseMultiError, or nil if none found.
func (m *DeleteDemoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDemoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeleteDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeleteDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeleteDemoResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeleteDemoResponseMultiError(errors)
	}

	return nil
}

// DeleteDemoResponseMultiError is an error wrapping multiple validation errors
// returned by DeleteDemoResponse.ValidateAll() if the designated constraints
// aren't met.
type DeleteDemoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDemoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDemoResponseMultiError) AllErrors() []error { return m }

// DeleteDemoResponseValidationError is the validation error returned by
// DeleteDemoResponse.Validate if the designated constraints aren't met.
type DeleteDemoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDemoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDemoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDemoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDemoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDemoResponseValidationError) ErrorName() string {
	return "DeleteDemoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDemoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDemoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDemoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDemoResponseValidationError{}

// Validate checks the field values on ListDemoRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListDemoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDemoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDemoRequestMultiError, or nil if none found.
func (m *ListDemoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDemoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPage() != 0 {

		if m.GetPage() < 1 {
			err := ListDemoRequestValidationError{
				field:  "Page",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetPageSize() != 0 {

		if val := m.GetPageSize(); val < 1 || val > 100 {
			err := ListDemoRequestValidationError{
				field:  "PageSize",
				reason: "value must be inside range [1, 100]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for Name

	if m.Status != nil {

		if m.GetStatus() != 0 {

			if _, ok := _ListDemoRequest_Status_InLookup[m.GetStatus()]; !ok {
				err := ListDemoRequestValidationError{
					field:  "Status",
					reason: "value must be in list [1 2]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(errors) > 0 {
		return ListDemoRequestMultiError(errors)
	}

	return nil
}

// ListDemoRequestMultiError is an error wrapping multiple validation errors
// returned by ListDemoRequest.ValidateAll() if the designated constraints
// aren't met.
type ListDemoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDemoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDemoRequestMultiError) AllErrors() []error { return m }

// ListDemoRequestValidationError is the validation error returned by
// ListDemoRequest.Validate if the designated constraints aren't met.
type ListDemoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDemoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDemoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDemoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDemoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDemoRequestValidationError) ErrorName() string { return "ListDemoRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListDemoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDemoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDemoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDemoRequestValidationError{}

var _ListDemoRequest_Status_InLookup = map[int32]struct{}{
	1: {},
	2: {},
}

// Validate checks the field values on ListDemoData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListDemoData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDemoData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListDemoDataMultiError, or
// nil if none found.
func (m *ListDemoData) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDemoData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListDemoDataValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListDemoDataValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListDemoDataValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Total

	// no validation rules for TotalPages

	if len(errors) > 0 {
		return ListDemoDataMultiError(errors)
	}

	return nil
}

// ListDemoDataMultiError is an error wrapping multiple validation errors
// returned by ListDemoData.ValidateAll() if the designated constraints aren't met.
type ListDemoDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDemoDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDemoDataMultiError) AllErrors() []error { return m }

// ListDemoDataValidationError is the validation error returned by
// ListDemoData.Validate if the designated constraints aren't met.
type ListDemoDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDemoDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDemoDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDemoDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDemoDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDemoDataValidationError) ErrorName() string { return "ListDemoDataValidationError" }

// Error satisfies the builtin error interface
func (e ListDemoDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDemoData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDemoDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDemoDataValidationError{}

// Validate checks the field values on ListDemoResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListDemoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDemoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDemoResponseMultiError, or nil if none found.
func (m *ListDemoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDemoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListDemoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListDemoResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListDemoResponseMultiError(errors)
	}

	return nil
}

// ListDemoResponseMultiError is an error wrapping multiple validation errors
// returned by ListDemoResponse.ValidateAll() if the designated constraints
// aren't met.
type ListDemoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDemoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDemoResponseMultiError) AllErrors() []error { return m }

// ListDemoResponseValidationError is the validation error returned by
// ListDemoResponse.Validate if the designated constraints aren't met.
type ListDemoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDemoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDemoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDemoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDemoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDemoResponseValidationError) ErrorName() string { return "ListDemoResponseValidationError" }

// Error satisfies the builtin error interface
func (e ListDemoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDemoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDemoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDemoResponseValidationError{}
