// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: demo/v1/demo.proto

package demov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "golang-tars/pkg/proto/demo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DemoServiceName is the fully-qualified name of the DemoService service.
	DemoServiceName = "demo.v1.DemoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DemoServiceCreateDemoProcedure is the fully-qualified name of the DemoService's CreateDemo RPC.
	DemoServiceCreateDemoProcedure = "/demo.v1.DemoService/CreateDemo"
	// DemoServiceGetDemoProcedure is the fully-qualified name of the DemoService's GetDemo RPC.
	DemoServiceGetDemoProcedure = "/demo.v1.DemoService/GetDemo"
	// DemoServiceUpdateDemoProcedure is the fully-qualified name of the DemoService's UpdateDemo RPC.
	DemoServiceUpdateDemoProcedure = "/demo.v1.DemoService/UpdateDemo"
	// DemoServiceDeleteDemoProcedure is the fully-qualified name of the DemoService's DeleteDemo RPC.
	DemoServiceDeleteDemoProcedure = "/demo.v1.DemoService/DeleteDemo"
	// DemoServiceListDemoProcedure is the fully-qualified name of the DemoService's ListDemo RPC.
	DemoServiceListDemoProcedure = "/demo.v1.DemoService/ListDemo"
)

// DemoServiceClient is a client for the demo.v1.DemoService service.
type DemoServiceClient interface {
	// 创建 Demo
	CreateDemo(context.Context, *connect.Request[v1.CreateDemoRequest]) (*connect.Response[v1.CreateDemoResponse], error)
	// 获取 Demo
	GetDemo(context.Context, *connect.Request[v1.GetDemoRequest]) (*connect.Response[v1.GetDemoResponse], error)
	// 更新 Demo
	UpdateDemo(context.Context, *connect.Request[v1.UpdateDemoRequest]) (*connect.Response[v1.UpdateDemoResponse], error)
	// 删除 Demo
	DeleteDemo(context.Context, *connect.Request[v1.DeleteDemoRequest]) (*connect.Response[v1.DeleteDemoResponse], error)
	// 列表 Demo
	ListDemo(context.Context, *connect.Request[v1.ListDemoRequest]) (*connect.Response[v1.ListDemoResponse], error)
}

// NewDemoServiceClient constructs a client for the demo.v1.DemoService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDemoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DemoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	demoServiceMethods := v1.File_demo_v1_demo_proto.Services().ByName("DemoService").Methods()
	return &demoServiceClient{
		createDemo: connect.NewClient[v1.CreateDemoRequest, v1.CreateDemoResponse](
			httpClient,
			baseURL+DemoServiceCreateDemoProcedure,
			connect.WithSchema(demoServiceMethods.ByName("CreateDemo")),
			connect.WithClientOptions(opts...),
		),
		getDemo: connect.NewClient[v1.GetDemoRequest, v1.GetDemoResponse](
			httpClient,
			baseURL+DemoServiceGetDemoProcedure,
			connect.WithSchema(demoServiceMethods.ByName("GetDemo")),
			connect.WithClientOptions(opts...),
		),
		updateDemo: connect.NewClient[v1.UpdateDemoRequest, v1.UpdateDemoResponse](
			httpClient,
			baseURL+DemoServiceUpdateDemoProcedure,
			connect.WithSchema(demoServiceMethods.ByName("UpdateDemo")),
			connect.WithClientOptions(opts...),
		),
		deleteDemo: connect.NewClient[v1.DeleteDemoRequest, v1.DeleteDemoResponse](
			httpClient,
			baseURL+DemoServiceDeleteDemoProcedure,
			connect.WithSchema(demoServiceMethods.ByName("DeleteDemo")),
			connect.WithClientOptions(opts...),
		),
		listDemo: connect.NewClient[v1.ListDemoRequest, v1.ListDemoResponse](
			httpClient,
			baseURL+DemoServiceListDemoProcedure,
			connect.WithSchema(demoServiceMethods.ByName("ListDemo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// demoServiceClient implements DemoServiceClient.
type demoServiceClient struct {
	createDemo *connect.Client[v1.CreateDemoRequest, v1.CreateDemoResponse]
	getDemo    *connect.Client[v1.GetDemoRequest, v1.GetDemoResponse]
	updateDemo *connect.Client[v1.UpdateDemoRequest, v1.UpdateDemoResponse]
	deleteDemo *connect.Client[v1.DeleteDemoRequest, v1.DeleteDemoResponse]
	listDemo   *connect.Client[v1.ListDemoRequest, v1.ListDemoResponse]
}

// CreateDemo calls demo.v1.DemoService.CreateDemo.
func (c *demoServiceClient) CreateDemo(ctx context.Context, req *connect.Request[v1.CreateDemoRequest]) (*connect.Response[v1.CreateDemoResponse], error) {
	return c.createDemo.CallUnary(ctx, req)
}

// GetDemo calls demo.v1.DemoService.GetDemo.
func (c *demoServiceClient) GetDemo(ctx context.Context, req *connect.Request[v1.GetDemoRequest]) (*connect.Response[v1.GetDemoResponse], error) {
	return c.getDemo.CallUnary(ctx, req)
}

// UpdateDemo calls demo.v1.DemoService.UpdateDemo.
func (c *demoServiceClient) UpdateDemo(ctx context.Context, req *connect.Request[v1.UpdateDemoRequest]) (*connect.Response[v1.UpdateDemoResponse], error) {
	return c.updateDemo.CallUnary(ctx, req)
}

// DeleteDemo calls demo.v1.DemoService.DeleteDemo.
func (c *demoServiceClient) DeleteDemo(ctx context.Context, req *connect.Request[v1.DeleteDemoRequest]) (*connect.Response[v1.DeleteDemoResponse], error) {
	return c.deleteDemo.CallUnary(ctx, req)
}

// ListDemo calls demo.v1.DemoService.ListDemo.
func (c *demoServiceClient) ListDemo(ctx context.Context, req *connect.Request[v1.ListDemoRequest]) (*connect.Response[v1.ListDemoResponse], error) {
	return c.listDemo.CallUnary(ctx, req)
}

// DemoServiceHandler is an implementation of the demo.v1.DemoService service.
type DemoServiceHandler interface {
	// 创建 Demo
	CreateDemo(context.Context, *connect.Request[v1.CreateDemoRequest]) (*connect.Response[v1.CreateDemoResponse], error)
	// 获取 Demo
	GetDemo(context.Context, *connect.Request[v1.GetDemoRequest]) (*connect.Response[v1.GetDemoResponse], error)
	// 更新 Demo
	UpdateDemo(context.Context, *connect.Request[v1.UpdateDemoRequest]) (*connect.Response[v1.UpdateDemoResponse], error)
	// 删除 Demo
	DeleteDemo(context.Context, *connect.Request[v1.DeleteDemoRequest]) (*connect.Response[v1.DeleteDemoResponse], error)
	// 列表 Demo
	ListDemo(context.Context, *connect.Request[v1.ListDemoRequest]) (*connect.Response[v1.ListDemoResponse], error)
}

// NewDemoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDemoServiceHandler(svc DemoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	demoServiceMethods := v1.File_demo_v1_demo_proto.Services().ByName("DemoService").Methods()
	demoServiceCreateDemoHandler := connect.NewUnaryHandler(
		DemoServiceCreateDemoProcedure,
		svc.CreateDemo,
		connect.WithSchema(demoServiceMethods.ByName("CreateDemo")),
		connect.WithHandlerOptions(opts...),
	)
	demoServiceGetDemoHandler := connect.NewUnaryHandler(
		DemoServiceGetDemoProcedure,
		svc.GetDemo,
		connect.WithSchema(demoServiceMethods.ByName("GetDemo")),
		connect.WithHandlerOptions(opts...),
	)
	demoServiceUpdateDemoHandler := connect.NewUnaryHandler(
		DemoServiceUpdateDemoProcedure,
		svc.UpdateDemo,
		connect.WithSchema(demoServiceMethods.ByName("UpdateDemo")),
		connect.WithHandlerOptions(opts...),
	)
	demoServiceDeleteDemoHandler := connect.NewUnaryHandler(
		DemoServiceDeleteDemoProcedure,
		svc.DeleteDemo,
		connect.WithSchema(demoServiceMethods.ByName("DeleteDemo")),
		connect.WithHandlerOptions(opts...),
	)
	demoServiceListDemoHandler := connect.NewUnaryHandler(
		DemoServiceListDemoProcedure,
		svc.ListDemo,
		connect.WithSchema(demoServiceMethods.ByName("ListDemo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/demo.v1.DemoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DemoServiceCreateDemoProcedure:
			demoServiceCreateDemoHandler.ServeHTTP(w, r)
		case DemoServiceGetDemoProcedure:
			demoServiceGetDemoHandler.ServeHTTP(w, r)
		case DemoServiceUpdateDemoProcedure:
			demoServiceUpdateDemoHandler.ServeHTTP(w, r)
		case DemoServiceDeleteDemoProcedure:
			demoServiceDeleteDemoHandler.ServeHTTP(w, r)
		case DemoServiceListDemoProcedure:
			demoServiceListDemoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDemoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDemoServiceHandler struct{}

func (UnimplementedDemoServiceHandler) CreateDemo(context.Context, *connect.Request[v1.CreateDemoRequest]) (*connect.Response[v1.CreateDemoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.CreateDemo is not implemented"))
}

func (UnimplementedDemoServiceHandler) GetDemo(context.Context, *connect.Request[v1.GetDemoRequest]) (*connect.Response[v1.GetDemoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.GetDemo is not implemented"))
}

func (UnimplementedDemoServiceHandler) UpdateDemo(context.Context, *connect.Request[v1.UpdateDemoRequest]) (*connect.Response[v1.UpdateDemoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.UpdateDemo is not implemented"))
}

func (UnimplementedDemoServiceHandler) DeleteDemo(context.Context, *connect.Request[v1.DeleteDemoRequest]) (*connect.Response[v1.DeleteDemoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.DeleteDemo is not implemented"))
}

func (UnimplementedDemoServiceHandler) ListDemo(context.Context, *connect.Request[v1.ListDemoRequest]) (*connect.Response[v1.ListDemoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.ListDemo is not implemented"))
}
