// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/google/wire"
	"golang-tars/internal/user/data/mysql/dao"
	"golang-tars/internal/user/handler"
	"golang-tars/internal/user/proxy"
	"golang-tars/internal/user/service"
)

// Injectors from wire.go:

// InitializeHandler 初始化 Handler
// Wire 会自动生成这个函数的实现，解析所有依赖关系
// 生成的代码在 wire_gen.go 文件中
func InitializeHandler() (*handler.DemoHandler, error) {
	manager := ProvideDBManager()
	demoDAO, err := dao.NewDemoDAO(manager)
	if err != nil {
		return nil, err
	}
	demoProxyConfig := ProvideDemoProxyConfig()
	demoProxy := proxy.NewDemoProxy(demoProxyConfig)
	demoService := service.NewDemoService(demoDAO, demoProxy)
	demoHandler := handler.NewDemoHandler(demoService)
	return demoHandler, nil
}

// wire.go:

// ProviderSet 定义所有的依赖注入 Provider
// Wire 会按照依赖关系自动排序并生成初始化代码
var ProviderSet = wire.NewSet(

	ProvideDBManager,
	ProvideDemoProxyConfig, dao.NewDemoDAO, dao.NewUserDAO, dao.NewUserLoginLogDAO, proxy.NewDemoProxy, service.NewDemoService, handler.NewDemoHandler,
)
