APP       := Demo
TARGET    := UserServer
MFLAGS    :=
DFLAGS    :=
CONFIG    := client
STRIP_FLAG:= N
J2GO_FLAG:= 

-include scripts/makefile.tars.gomod.mk


TARS_WEB_HOST   := http://8.141.7.34:3000
TARS_WEB_TOKEN  := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhZG1pbiIsImlhdCI6MTc0MTg1OTY5NSwiZXhwIjoxODM2NTU0MDk1fQ.jePWFqoXIGFZpI-6QO6Kepr3A7t9fXPCe06iYKvi5Nk"
UPLOAD_USER   := $(shell whoami)
UPLOAD_OS     := linux

